"""empty message

Revision ID: 6b20a9bc5559
Revises: 
Create Date: 2018-03-18 18:33:45.817028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b20a9bc5559'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('google_credentials',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('credentials_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('google_credentials')
    # ### end Alembic commands ###
