"""empty message

Revision ID: bf19592f4a53
Revises: bebc7baaa619
Create Date: 2018-03-16 02:02:10.611516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf19592f4a53'
down_revision = 'bebc7baaa619'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('compiler_output', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission', 'compiler_output')
    # ### end Alembic commands ###
